#!/bin/sh

### BEGIN INIT INFO
# Provides:     preinit
# Required-Start:   $remote_fs $syslog
# Required-Stop:    $remote_fs $syslog
# Default-Start:    2 3 4 5
# Default-Stop:     
# Short-Description:    preinit
### END INIT INFO

start() {
	echo -n "Starting hwclock: "
    if [ ! -d /home/asterisk ];then mkdir /home/asterisk;fi
    rm -rf /tmp/asterisk && ln -sf /home/asterisk /tmp/asterisk
    hwclock -s
	echo "OK"
}

stop() {
	echo "OK"
}

restart() {
	stop
	sleep 1
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
