#!/bin/sh

### BEGIN INIT INFO
# Provides:     asterisk
# Required-Start:   $remote_fs $syslog
# Required-Stop:    $remote_fs $syslog
# Default-Start:    2 3 4 5
# Default-Stop:     
# Short-Description:    asterisk
### END INIT INFO

logdir() {
    if [ ! -d /var/log/asterisk/cdr-csv ];then mkdir -p /var/log/asterisk/cdr-csv;fi
}

start() {
	echo -n "Starting asterisk: "
	logdir
	modprobe dahdi
	start-stop-daemon -S -x /usr/sbin/asterisk
	echo "OK"
}

stop() {
	echo -n "Stopping asterisk: "
	start-stop-daemon -K -x /usr/sbin/asterisk
	modprobe -r dahdi
	echo "OK"
}

restart() {
	stop
	sleep 1
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
