#!/bin/sh

### BEGIN INIT INFO
# Provides:     ntp
# Required-Start:   $remote_fs $syslog
# Required-Stop:    $remote_fs $syslog
# Default-Start:    2 3 4 5
# Default-Stop:     
# Short-Description:    ntp
### END INIT INFO

start() {
	echo -n "Starting ntp: "
	start-stop-daemon -S -x /usr/sbin/ntpd -- -g
	echo "OK"
}

stop() {
	echo -n "Stopping ntp: "
	start-stop-daemon -K -x /usr/sbin/ntpd -- -g
	echo "OK"
}

restart() {
	stop
	sleep 1
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
